LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

ifneq ($(ANDROID_API_LP_OR_LATER),true)
ifeq ($(TARGET_BOARD_OMAP_CPU),4470)
LOCAL_SGX_CORE := 544_112
else
LOCAL_SGX_CORE := 540_120
endif
endif

LOCAL_SRC_FILES := egl.c
LOCAL_CFLAGS := -Wall -Werror
LOCAL_LDFLAGS := -L $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)
ifeq ($(ANDROID_API_LP_OR_LATER),true)
LOCAL_ADDITIONAL_DEPENDENCIES := libIMGegl
LOCAL_LDFLAGS += $(LOCAL_ADDITIONAL_DEPENDENCIES:lib%=-l%)
else
LOCAL_LDFLAGS += -lIMGegl_SGX$(LOCAL_SGX_CORE)
libEGL_POWERVR_SGX54X: $(TARGET_OUT_VENDOR)/lib/libIMGegl_SGX$(LOCAL_SGX_CORE).so
endif
LOCAL_MODULE := libEGL_POWERVR_SGX54X

LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)/egl
LOCAL_MODULE_TAGS := optional

include $(BUILD_SHARED_LIBRARY)
